### ISSUE TITLE
Неверный перевод

### ISSUE THREAD

**Issue by 2epeat** [php/doc-ru#1019]
From manual page: https://php.net/language.oop5.interfaces

---

https://www.php.net/manual/ru/language.oop5.interfaces.php
В предложении: 
«Класс обязан реализовать каждый метод интерфейса; _при выполнении_ требования PHP выдаст фатальную ошибку.»
_при выполнении_ следует заменить на **невыполнении**.

**Comment by saundefined** [comment]
Спасибо!
