### ISSUE TITLE
typo: ошибка в примере

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [php/doc-ru#349]
From manual page: https://php.net/language.types.string

Пример #7 Пример правильного синтаксиса, даже до PHP 7.3.0
<?php
class foo {
    public $bar = <<<EOT
bar
    EOT;
}
?>

-->
"EOT;" должна быть без отступа!

**Comment by saundefined** [comment]
Спасибо!

**Comment by aleksandr-shevchenko** [comment]
Там же.
Тип ресурс (resource) _всегда всегда_ преобразуется в строку (string) вида...
