### ISSUE TITLE
token_get_all() returns incorrect token for class constant with name STATIC

### ISSUE THREAD

**Issue by Kasp42** [php/doc-ru#359]
From manual page: https://php.net/tokens

---
function token_get_all() return T_STATIC for class constant with name STATIC
```
<?php

class A {
  public const STATIC = 1;
}

?>
```

**Comment by saundefined** [comment]
Thanks for the issue,
you can use the `TOKEN_PARSE` flag to recognize reserved words.

https://3v4l.org/p2beB
