### ISSUE TITLE
Ошибка в абзаце про приведение типов

### ISSUE THREAD

**Issue by vdme** [php/doc-ru#367]
From manual page: https://php.net/language.types.float

---
Исходный текст:

> Если строка содержащая число или **ведущая числовая**, тогда она будет преобразована в соответствующее **целочисленное значение**, в противном случае она преобразуется в ноль (0).

Предлагаю следующий текст:

> Если строка содержит число или ведущую числовую последовательность, тогда она будет преобразована в соответствующее значение с плавающей точкой, в противном случае она преобразуется в ноль (0).

**Comment by saundefined** [comment]
Спасибо!
