### ISSUE TITLE
Error in russian translation

### ISSUE THREAD

**Issue by aperturer** [php/doc-ru#369]
From manual page: https://php.net/function.set-error-handler

---

in English mode: 

>  error_levels 
> Can be used to mask the triggering of the callback function just like the error_reporting ini setting controls which errors are shown. 

in Russian mode this text is:

>  callback 
> Может использоваться для задания маски, в соответствии с которой будет вызываться error_handler, по аналогии с ini-настройкой error_reporting, которая отвечает за то, какие ошибки будут показаны в отчёте.

No "callback"! Parameter is "error_levels". Callback description already exist higher on the page.

**Comment by saundefined** [comment]
Thank you!
