### ISSUE TITLE
Опечатка на странице fetchColumn в примере

### ISSUE THREAD

**Issue by MioVisman** [php/doc-ru#375]
https://github.com/php/doc-ru/blob/master/reference/pdo/pdostatement/fetchcolumn.xml#L92

Требуется заменить
`Получение значения первого столбца второй строки`
на 
`Получение значения второго столбца второй строки`

как в 81 строке https://github.com/php/doc-ru/blob/master/reference/pdo/pdostatement/fetchcolumn.xml#L81

**Comment by saundefined** [comment]
Спасибо!
