### ISSUE TITLE
Устарели CHM файлы

### ISSUE THREAD

**Issue by WinterSilence** [php/doc-ru#407]
Хорошо бы прикрутить авто обновление [CHM файлов](https://www.php.net/download-docs.php) при обновлении репозитория.

**Comment by saundefined** [comment]
Они, насколько я помню, обновляются вместе с самим php.net (тоже не CI, а просто задания на кроне).
Чтобы переделать механику, сначала, лучше обсудить в @internals =)

В этом репозитории максимум, что можем сделать — добавить сборку CHM на GitHub Actions и, например, указывать ссылку в README на последний собранный файл
