### ISSUE TITLE
Eerror [pecl install radius]

### ISSUE THREAD

**Issue by gato-gto** [php/doc-ru#412]
`/usr/include/php/20190902/Zend/zend_API.h:629: note: macro "RETVAL_STRINGL" defined here
  629 | #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
      |
/tmp/pear/temp/radius/radius.c:785:3: error: ‘RETVAL_STRINGL’ undeclared (first use in this function)
  785 |   RETVAL_STRINGL((char *) buf, len, 1);
      |   ^~~~~~~~~~~~~~
/tmp/pear/temp/radius/radius.c: In function ‘zif_radius_demangle_mppe_key’:
/tmp/pear/temp/radius/radius.c:806:31: error: expected expression before ‘radius_descriptor’
  806 |  ZEND_FETCH_RESOURCE(raddesc, radius_descriptor *, &z_radh, -1, "rad_handle", le_radius);
      |                               ^~~~~~~~~~~~~~~~~
/tmp/pear/temp/radius/radius.c:814:39: error: macro "RETVAL_STRINGL" passed 3 arguments, but takes just 2
  814 |   RETVAL_STRINGL((char *) buf, dlen, 1);
      |                                       ^
In file included from /usr/include/php/20190902/main/php.h:38,
                 from /tmp/pear/temp/radius/radius.c:38:
/usr/include/php/20190902/Zend/zend_API.h:629: note: macro "RETVAL_STRINGL" defined here
  629 | #define RETVAL_STRINGL(s, l)    ZVAL_STRINGL(return_value, s, l)
      |
/tmp/pear/temp/radius/radius.c:814:3: error: ‘RETVAL_STRINGL’ undeclared (first use in this function)
  814 |   RETVAL_STRINGL((char *) buf, dlen, 1);
      |   ^~~~~~~~~~~~~~
/tmp/pear/temp/radius/radius.c: At top level:
/tmp/pear/temp/radius/radius.c:844:20: error: unknown type name ‘zend_rsrc_list_entry’; did you mean ‘zend_rsrc_list_dtors_entry’?
  844 | void _radius_close(zend_rsrc_list_entry *rsrc TSRMLS_DC)
      |                    ^~~~~~~~~~~~~~~~~~~~
      |                    zend_rsrc_list_dtors_entry
make: *** [Makefile:191: radius.lo] Error 1
ERROR: `make' failed`

**Comment by saundefined** [comment]
Hi, this doesn't seem to be a problem with the Russian documentation.
[LawnGnome/php-radius](https://github.com/LawnGnome/php-radius) is the better place to report a bug.
