### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by yest13** [php/doc-ru#418]
From manual page: https://php.net/function.get-class-methods
in example "Example #1 get_class_methods() example"
the result should be:

__construct
myfunc1
myfunc2

, but you have an error on the first line ("myclass" instead of "__construct").

---
P.S. sorry if i'm wrong, i just started learning.

**Comment by saundefined** [comment]
@yest13 good catch! You're absolutely right.
The error has been fixed, it will soon be updated on the site
