### ISSUE TITLE
Правка последнего примера

### ISSUE THREAD

**Issue by maximniko** [php/doc-ru#419]
From manual page: https://www.php.net/manual/ru/language.types.array

---
$arr1 = array(2, 3);
$arr2 = $arr1;
$arr2[] = 4; // $arr2 изменился,
             // $arr1 всё ещё array(2, 3)

$arr3 = &$arr1;
$arr3[] = 4; // теперь $arr1 и $arr3 одинаковы

В примере выше массивы $arr1 и $arr3 становятся одинаковыми на предыдущей строке (делаем т.к. в переменную передаем ссылку). На последней строке становятся одинаковы массивы $arr1 и $arr2.  

Еще можно для примера дописать unset($arr3) и показать, что массив 1 остается измененным

**Comment by saundefined** [comment]
Спасибо, на данный момент пример соответствует английской версии.
Для улучшения примера, лучше отправить PR в [php/doc-en](https://github.com/php/doc-en).
