### ISSUE TITLE
Small text bug

### ISSUE THREAD

**Issue by Elmo00** [php/doc-ru#466]
From manual page: https://php.net/language.types.numeric-strings
On the page, when using the translation language "Russian", part of the example comments in the "Behavior before PHP 8.0.0" field goes beyond the area of the code window.
Observed in several different browsers.
Example:
![image](https://user-images.githubusercontent.com/79865000/225261230-aaad1c4f-3c10-4c99-a461-451af13d8202.png)

---

**Comment by saundefined** [comment]
Hi, thanks for the issue,

The layout is independent of the documentation,
code protruding beyond the page is a known problem in [web-php](https://github.com/php/web-php)
