### ISSUE TITLE
Wrong form of word

### ISSUE THREAD

**Issue by NikitaMarakushev** [php/doc-ru#471]
From manual page: https://php.net/intro.phpdbg

"Поскольку phpdbg реализован в виде модуля SAPI, то он может полностью контролировать окружение без воздействие на функциональность и скорость выполнения вашего кода." - is not correct

"Поскольку phpdbg реализован в виде модуля SAPI, то он может полностью контролировать окружение без воздействия на функциональность и скорость выполнения вашего кода." - is correct

---

**Comment by saundefined** [comment]
Спасибо!
