### ISSUE TITLE
In the last usage example, in Russian, the line length is incorrect (19 instead of 10 characters)

### ISSUE THREAD

**Issue by pivasikkost** [php/doc-ru#485]
From manual page: https://php.net/function.array-reduce

---
![изображение](https://github.com/php/doc-ru/assets/6388795/8bf1bf13-1a26-4fb7-a4c2-31ba674cfaec)

**Comment by u-mulder** [comment]
Это многобайтовая кодировка, так что все тут правильно.
@saundefined Предлагаю закрыть.
