### ISSUE TITLE
[Ошибка перевода] Отсутствует перевод для операторов

### ISSUE THREAD

**Issue by MioVisman** [php/doc-ru#535]
### Страница с опечаткой

https://www.php.net/manual/ru/language.operators.php

### Описание ошибки

Страницы на которые ведут ссылки из содержимого отсутствуют в переводе.
Вот этой папки https://github.com/php/doc-en/tree/master/language/operators не в ru версии.

**Comment by mmalferov** [comment]
Думаю, это ишью можно закрывать (по результатам https://github.com/php/doc-ru/pull/628)
