### ISSUE TITLE
Замена "Расширение" на "Модуль"

### ISSUE THREAD

**Issue by saundefined** [php/doc-ru#91]
Согласно [руководству](https://github.com/php/doc-ru/blob/master/CONTRIBUTING.md), "Extension" следует переводить как "модуль",

в старых переводах всё ещё часто встречается "расширение".

**Comment by zors1** [comment]
Если не ошибаюсь, то всё исправлено.

**Comment by saundefined** [comment]
@zors1, спасибо за помощь!
