### ISSUE TITLE
[Ошибка перевода]   array_intersect_assoc()

### ISSUE THREAD

**Issue by AndryG** [php/doc-ru#917]
### Страница с опечаткой

https://www.php.net/manual/ru/function.array-intersect-assoc.php

### Описание ошибки

 array_intersect_assoc(), в отличии от  array_intersect(), сравнивает не только значение, но и ключи. В переводе этот момент упущен.

### Ваш вариант перевода

Функция array_intersect_assoc() возвращает массив, содержащий все значения массива array, которые содержатся во всех переданных аргументах. Обратите внимание, что сравниваются **также и** ключи, в отличие от функции [array_intersect()](https://www.php.net/manual/ru/function.array-intersect.php).

**Comment by u-mulder** [comment]
Ты можешь самостоятельно оформить PR, файл тут https://github.com/php/doc-ru/blob/master/reference/array/functions/array-intersect-key.xml
