### ISSUE TITLE
Исправьте опечатку 

### ISSUE THREAD

**Issue by mkolotovich** [php/doc-ru#975]
From manual page: https://php.net/function.rand

---
Исправьте опечатку в этом тексте - <html>
<body>

В функции rand() **испрвили** ошибку
--

</body>
</html>В функции rand() [испрвили ошибку](https://www.php.net/manual/ru/migration72.incompatible.php#migration72.incompatible.rand-mt_rand-output)

**Comment by mmalferov** [comment]
Спасибо за сигнал. Опечатку исправил:

https://github.com/php/doc-ru/commit/0bd7ab4e6de343099e7c25d5540c2c63fa54929c
