### ISSUE TITLE
A typo in the word

### ISSUE THREAD

**Issue by velmesov** [php/doc-ru#976]
From manual page: https://php.net/function.debug-backtrace

---
Hello!

In the text "Нужно ли заполнять ключ "object" (в выходом массиве)." - a typo.
It should be like this: "Нужно ли заполнять ключ "object" (в выходном массиве)."

![php_bag_translate](https://github.com/php/doc-ru/assets/13731308/fdae328d-e209-4a3d-888a-50c3ca1a1d4b)

**Comment by saundefined** [comment]
Good catch, thanks!
