### ISSUE TITLE
The link does not exist (service Maxmind)

### ISSUE THREAD

**Issue by velmesov** [php/doc-ru#980]
From manual page: https://php.net/geoip.requirements

---
Hello!

This link is no longer working: http://www.maxmind.com/app/c

And it may be worth checking other information about the Maxmind service in the documentation, perhaps something is no longer relevant.

![image](https://github.com/user-attachments/assets/ed0a4952-0a21-4bb6-ac47-eb6b20b885b2)

**Comment by velmesov** [comment]
In addition, here's what I found on their off-site. It is not necessary to compile the library, you can connect it through the composer.

Detailed instructions for connecting here - https://dev.maxmind.com/geoip/geolocate-an-ip/databases

![image](https://github.com/user-attachments/assets/6946601b-d921-4668-8652-3992fd7733bb)

**Comment by saundefined** [comment]
Thanks for the clarification!
This is better addressed to [doc-en](https://github.com/php/doc-en/).
