### ISSUE TITLE
Вступительная страница инструмента перевода отправляет к мертвому списку рассылки

### ISSUE THREAD

**Issue by mmalferov** [php/doc-ru#984]
Вступительная страница русского инструмента перевода

http://doc.php.net/revcheck.php?lang=ru

предлагает присоединиться к команде переводчиков PHP-документации
на русский язык через список рассылки: `doc-ru@lists.php.net`

Но страница списка `php.doc.ru` говорит, что список закрылся и больше
не принимает ни подписчиков, ни новые публикации:

https://news-web.php.net/php.doc.ru

Может быть, на вступительной странице вместо упоминания мертвого списка рассылки
оставить инструкцию, которая пригласит на [Гитхаб](https://github.com/php/doc-ru)
и посоветует отправлять исправления сразу со страниц документации? :-)

**Comment by saundefined** [comment]
Хм... какая-то ошибка, наверное.
Остальные списки активных языков остались рабочими, сейчас уточню.

**Comment by saundefined** [comment]
В любом случае, страницу можно переработать,
слак, думаю, смело можно уже убирать, по списку рассылки подождём ответа.

**Comment by saundefined** [comment]
@mmalferov спасибо, что заметил недоступность списка рассылок – поправили :)

**Comment by mmalferov** [comment]
Пока исправил страницу вот так: http://doc.php.net/revcheck.php?lang=ru

Готов изменить или добавить содержание, если что-то упустил ;-)

Не нашел способа разбить текст страницы на абзацы лучше, чем заинлайнить span-элементы со style-атрибутами: исходный код, который обрабатывает страницу, вставляет содержание intro-тега в p-элемент:

https://github.com/php/web-doc/blob/a642d7846b8f34d2d23f9bcc49f7bfb5663e3f7e/www/revcheck.php#L445

чем не дает нормально отформатировать страницу. Теги `<para>` или `<simpara>` в документе не обрабатываются.

Включение div-элементов внутрь p-элементов нарушает семантику, поэтому остановился на тегах span, поскольку других тегов не нашел, а текст без разбивки на абзацы затрудняет чтение; читатель не виноват ))

Было бы проще, если бы обработчик страницы оборачивал intro-содерание в тот же div. Тогда получилось бы обернуть текущее содержание тега intro в каждом языке в тег p, чтобы не нарушить вывод текущей разметки (я бы это руками сделал за 5 минут и отправил PR). И тогда бы на выходе разметка intrl-блока выглядела вот так, например, для французской версии:

```
<div>
  <p>
    Ceci est le fichier généré par phpdoc-fr/scripts/revcheck.php.
    Il vous permet de voir rapidement quels sont les fichiers qui
    doivent être mis à jour ainsi que la personne qui s'en occupe.
  </p>
</div>
```

Тогда разбивай вступительную страницу на абзацы без span'ов с инлайн-стилями =)

Ну или а) не бить на абзацы и мучить читателя, или б) оставить span'ы. Хотя лучше всё-таки подумать, как сделать удобно каждому: и тем, кому достаточно одного абзаца, и тем, кому требуется два и больше ))
