### ISSUE TITLE
Wrong var name in ftp example basic page

### ISSUE THREAD

**Issue by realtek2** [php/doc-ru#992]
From manual page: https://php.net/ftp.examples-basic

---
Should be corrected to `ftp_close($ftp);`

![image](https://github.com/user-attachments/assets/4cd353b9-3cf6-411d-ba83-670c11a489a1)

**Comment by realtek2** [comment]
пытался создать пул реквест, но ловлю 403)

**Comment by saundefined** [comment]
Спасибо!

**Comment by saundefined** [comment]
> пытался создать пул реквест, но ловлю 403)

Странно, а в какой момент ошибка?

**Comment by realtek2** [comment]
![image](https://github.com/user-attachments/assets/1e6ed175-9b5c-4df0-bf5b-270daa762b07)
когда пушу

**Comment by saundefined** [comment]
Напрямую не даст запушить, надо форкнуть репозиторий, например, `realtek2/doc-ru` и запушить туда,
потом PR из своей копии в основной репозиторий открыть.

https://docs.github.com/ru/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by realtek2** [comment]
понял, спасибо!!
